[module]
  [[module.imports]]
  path = "github.com/adityatelange/hugo-PaperMod"

[markup.goldmark.renderer]
  unsafe = true
  
baseURL = 'https://vgivanovic/vgivanovic.github.com'
languageCode = 'en-us'
title = 'Miscellaneous Amblings'
